-- CONTENT JOINED GENRE
SELECT *
FROM   CONTENT C
       JOIN GENRE G
         ON G.ID = C.GENRE_ID;

-- STAR JOINED CONTENT
SELECT *
FROM   STAR S
       JOIN STAR_CONTENT SC
         ON S.ID = SC.STAR_ID
       JOIN CONTENT C
         ON C.ID = SC.CONTENT_ID;